name: season_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^3.0.3
  go_router: ^16.2.5
  riverpod: ^3.0.3
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  connectivity_plus: ^7.0.0
  image_picker: ^1.2.0
  svg_image: ^0.0.5
  pinput: ^5.0.2
  country_code_picker: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/gif/
    - assets/images/svg/home/
    - assets/images/svg/chats/
    - assets/images/svg/trips/
    - assets/images/svg/user/
    - assets/images/png/
    - assets/images/png/weather/night/
    - assets/images/png/weather/day/
    - assets/translation/
    - assets/images/png/home/
    - assets/images/png/user/
    - assets/images/png/chats/
    - assets/images/png/contest/
    - assets/images/png/trips/
    - assets/images/png/side_menu/
    - assets/images/png/navigation/
    - assets/images/png/notifications/
    - assets/images/png/flights/
    - assets/images/svg/flights/


  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
        - asset: fonts/Cairo-Bold.ttf

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/core/localization/generated